[package]
name = "wasm-keys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf = { version = "0.11.2", features = ["macros"] }
web-sys = { version = "0.3.69", features = ["KeyboardEvent"] }
