
use phf::{phf_map, Map};
use crate::wasm_key::WasmKey;

pub static KEY_MAP: Map<&'static str, WasmKey> = phf_map! {
    "alt" => WasmKey::Alt,
    "altgraph" => WasmKey::AltGraph,
    "capslock" => WasmKey::CapsLock,
    "control" => WasmKey::Control,
    "fn" => WasmKey::Fn,
    "fnlock" => WasmKey::FnLock,
    "hyper" => WasmKey::Hyper,
    "meta" => WasmKey::Meta,

    // In Firefox, the Windows key is reported as "OS" instead of as "Meta". This will be changed in Firefox per Firefox bug 1232918
    "os" => WasmKey::Meta, // Note: Adjusted as per note for Firefox
    "numlock" => WasmKey::NumLock,
    "scrolllock" => WasmKey::ScrollLock,
    "shift" => WasmKey::Shift,
    "super" => WasmKey::Super,
    "symbol" => WasmKey::Symbol,
    "symbollock" => WasmKey::SymbolLock,

    "enter" => WasmKey::Enter,
    "tab" => WasmKey::Tab,
    " " => WasmKey::Space,

    "arrowdown" => WasmKey::ArrowDown,
    "arrowleft" => WasmKey::ArrowLeft,
    "arrowright" => WasmKey::ArrowRight,
    "arrowup" => WasmKey::ArrowUp,
    "end" => WasmKey::End,
    "home" => WasmKey::Home,
    "pagedown" => WasmKey::PageDown,
    "pageup" => WasmKey::PageUp,

    "backspace" => WasmKey::Backspace,
    "clear" => WasmKey::Clear,
    "copy" => WasmKey::Copy,
    "crsel" => WasmKey::CrSel,
    "cut" => WasmKey::Cut,
    "delete" => WasmKey::Delete,
    "eraseeof" => WasmKey::EraseEof,
    "exsel" => WasmKey::ExSel,
    "insert" => WasmKey::Insert,
    "paste" => WasmKey::Paste,
    "redo" => WasmKey::Redo,
    "undo" => WasmKey::Undo,

    "accept" => WasmKey::Accept,
    "again" => WasmKey::Again,
    "attn" => WasmKey::Attn,
    "cancel" => WasmKey::Cancel,
    "contextmenu" => WasmKey::ContextMenu,
    "escape" => WasmKey::Escape,
    "execute" => WasmKey::Execute,
    "find" => WasmKey::Find,
    "finish" => WasmKey::Finish,
    "help" => WasmKey::Help,
    "pause" => WasmKey::Pause,
    "play" => WasmKey::Play,
    "props" => WasmKey::Props,
    "select" => WasmKey::Select,
    "zoomin" => WasmKey::ZoomIn,
    "zoomout" => WasmKey::ZoomOut,

    "brightnessdown" => WasmKey::BrightnessDown,
    "brightnessup" => WasmKey::BrightnessUp,
    "eject" => WasmKey::Eject,
    "logoff" => WasmKey::LogOff,
    "power" => WasmKey::Power,
    "poweroff" => WasmKey::PowerOff,
    "printscreen" => WasmKey::PrintScreen,
    "hibernate" => WasmKey::Hibernate,
    "standby" => WasmKey::Standby,
    "wakeup" => WasmKey::WakeUp,

    "allcandidates" => WasmKey::AllCandidates,
    "alphanumeric" => WasmKey::Alphanumeric,
    "codeinput" => WasmKey::CodeInput,
    "compose" => WasmKey::Compose,
    "convert" => WasmKey::Convert,
    "dead" => WasmKey::Dead,
    "finalmode" => WasmKey::FinalMode,
    "groupfirst" => WasmKey::GroupFirst,
    "grouplast" => WasmKey::GroupLast,
    "groupnext" => WasmKey::GroupNext,
    "groupprevious" => WasmKey::GroupPrevious,
    "modechange" => WasmKey::ModeChange,
    "nextcandidate" => WasmKey::NextCandidate,
    "nonconvert" => WasmKey::NonConvert,
    "previouscandidate" => WasmKey::PreviousCandidate,
    "process" => WasmKey::Process,
    "singlecandidate" => WasmKey::SingleCandidate,

    "hangulmode" => WasmKey::HangulMode,
    "hanjamode" => WasmKey::HanjaMode,
    "junjamode" => WasmKey::JunjaMode,

    "eisu" => WasmKey::Eisu,
    "hankaku" => WasmKey::Hankaku,
    "hiragana" => WasmKey::Hiragana,
    "hiraganakatakana" => WasmKey::HiraganaKatakana,
    "kanamode" => WasmKey::KanaMode,
    "kanjimode" => WasmKey::KanjiMode,
    "katakana" => WasmKey::Katakana,
    "romaji" => WasmKey::Romaji,
    "zenkaku" => WasmKey::Zenkaku,
    "zenkakuhanaku" => WasmKey::ZenkakuHanaku,
};
